version:"3.9"
services:
  redis:
    image:redis:alpine
    ports:
      -"6379:6379"
  backend:
    build:./backend
    ports:
      -"5000:5000"
    environment:
      -REDIS_HOST=redis
    depends_on:
      -redis
  frontend:
    build:./frontend
    ports:
      -"3000:3000"
    stdin_open:true
    tty:true
    depends_on:
      -backend
